# Generated by Django 2.0 on 2017-12-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20171219_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tagline',
            new_name='content',
        ),
    ]
